# Generated by Django 3.1.7 on 2021-06-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210607_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contentDetail',
            field=models.TextField(default='', null=True),
        ),
    ]
